config/routes.rb
SkinnyMinnie::Application.routes.draw do
  get "cart/index"

  get "cart/show"

  get "product/index"

  get "product/show"

  get "products/index"

  get "products/show"

  get "products/category"

  get "users/index"

  get "dashboard/index"

  get "dashboard/my_rentals"

  get "dashboard/my_credits"

  get "dashboard/my_invites"

  get "dashboard/my_faves"

  get "dashboard/edit_profile"

  get "tsmhome/index"

  devise_for :users

  get "home/index"
  resources :users do
  match 'show/:id' => 'user#show'
  collection do
    get 'follow'
    get 'unfollow'
    get 'followers'
    get 'following'
  end

end

  
  

  

   root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  acts_as_follow_store
   
end

app/models/like.rb
class Like < ActiveRecord::Base
  acts_as_like_store
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  acts_as_mention_store
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_follower
  acts_as_followable
  acts_as_liker
  acts_as_mentionable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :id, :login, :username, :email, :password, :password_confirmation, :remember_me, :profile_private
  # attr_accessible :title, :body

	  # Virtual attribute for authenticating by either username or email
	# This is in addition to a real persisted field like 'username'
	attr_accessor :login

	 def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
  end

  def my_rentals
  end

  def my_credits
  end

  def my_invites
  end

  def my_faves
  end

  def edit_profile
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      render "tsm/index", :layout  => 'tsm' 
    else
      render "index"
  end

end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end

  def category
  end
end

app/controllers/tsm_controller.rb
class TsmController < ApplicationController

  def index
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
def index
  @users = User.all

  respond_to do |format|
    format.html # index.html.erb
    format.xml  { render :xml => @users }
    end
end

def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
end

def followers
     @user = User.find(params[:user])
     @followers = @user.followers(User)
   
     response = {:user => @user, :followers => @followers}
     
     respond_to do |format|
      format.html  #followers.html.erb
      format.xml {render :xml => response}
    end
end

def following
     @user = User.find(params[:user])
     @following = @user.followees(User)

     response = {:user => @user, :following => @following}
     
     respond_to do |format|
      format.html  #following.html.erb
      format.xml {render :xml => response}
    end
end

def follow
  #do something like
  user = User.find(params[:user])
  current_user.follow!(user)
  redirect_to :back
  flash[:success] = "Followed!"
end

def unfollow
  #do something like
  user = User.find(params[:user])
  current_user.unfollow!(user)
  redirect_to :back
  flash[:success] = "Unfollwed!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

   def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

  	
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
	
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tsm_helper.rb
module TsmHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/index.html.erb
<h1>Cart#index</h1>
<p>Find me in app/views/cart/index.html.erb</p>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

app/views/dashboard/edit_profile.html.erb
<h1>Dashboard#edit_profile</h1>
<p>Find me in app/views/dashboard/edit_profile.html.erb</p>

app/views/dashboard/index.html.erb
<div class="container">
	<div class="dashboard">
		<p>Username: <%= current_user.username %></p>
		<div class="top clearfix">
		<div class="profile-pic pull-left">
				<img src="/assets/nopicture.jpg">
		</div>
		

	<p>Name: <%= current_user.first_name %> <%= current_user.last_name %> </p>
	<p>Email: <%= current_user.email %></p>
	<p>Current Weight: <%= current_user.current_weight %></p>
	<p>Goal Weight: <%= current_user.goal_weight %></p>

	

		</div>
		<br>
		<% if current_user.followers(User).count > 0 %>
	   <%= link_to "Followers", followers_users_path(:user => current_user)%>
	  <% end %>
	  <% if current_user.followees(User).count > 0 %>
	   <%= link_to "Following", following_users_path(:user => current_user)%>
	  <% end %>
	  <br>
		<button type="button" class="btn btn-inverse" disabled>Followers: <%= current_user.followers(User).count %></button>

	</div>
</div>

app/views/dashboard/my_credits.html.erb
<h1>Dashboard#my_credits</h1>
<p>Find me in app/views/dashboard/my_credits.html.erb</p>

app/views/dashboard/my_faves.html.erb
<h1>Dashboard#my_faves</h1>
<p>Find me in app/views/dashboard/my_faves.html.erb</p>

app/views/dashboard/my_invites.html.erb
<h1>Dashboard#my_invites</h1>
<p>Find me in app/views/dashboard/my_invites.html.erb</p>

app/views/dashboard/my_rentals.html.erb
<h1>Dashboard#my_rentals</h1>
<p>Find me in app/views/dashboard/my_rentals.html.erb</p>

app/views/home/_loginandreg-box.html.erb
<div class="login-box">
  				<div class="left pull-left">
  					<%= render 'signin-form' %>
  				</div>
  				<div class="right pull-right">
  					<%= render 'register-form' %>
  				</div>
</div>

app/views/home/index.html.erb
<div class="body">
  		<div class="banner clear-fix">
  			<div class="banner1">
  				<div class="lede pull-left">UNLIMITED<br><span class="slogan">Clothing &amp; Accessories to fit  your Style</span></div>
  				<div class="price pull-right"><span class="start">*</span>$49<br><span class="monthly">per month</span></div></div>
  				<div class="invite-only pull-right">
  			</div>
  			</div>
  			
  		</div>

  	</div>
  	

app/views/product/index.html.erb
<h1>Product#index</h1>
<p>Find me in app/views/product/index.html.erb</p>

app/views/product/show.html.erb
<h1>Product#show</h1>
<p>Find me in app/views/product/show.html.erb</p>

app/views/products/category.html.erb
<h1>Products#category</h1>
<p>Find me in app/views/products/category.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/tsm/index.html.erb
<h1>this is home</h1>

app/views/users/followers.html.erb
<p><u>Followers</u></p>

<% @followers.each do |f| %> 
  <p> <%= link_to f.username, user_path(f) %> </p>
<% end %>

app/views/users/following.html.erb
<p><u>Followers</u></p>

<% @following.each do |f| %> 
  <p> <%= link_to f.username, user_path(f) %> </p>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<% if @user.id == current_user.id %>
<script type="text/javascript">
    window.location.href="/dashboard/index"  // put your correct path in a string here
  </script>
<% end %>
<div class="container">
	<div class="dashboard">
		<p>Username: <%= @user.username %></p>
		<div class="top clearfix">
		<div class="profile-pic pull-left">
				<img src="/assets/nopicture.jpg">
		</div>
		

<% if @user.profile_private == true && current_user.follows?(@user) == false %>
	<p>This users profile is PRIVATE</p>
<% else %>
	<p>Name: <%= @user.first_name %> <%= @user.last_name %> </p>
	<p>Email: <%= @user.email %></p>
	<p>Current Weight: <%= @user.current_weight %></p>
	<p>Goal Weight: <%= @user.goal_weight %></p>

	
	<% if current_user.follows?(@user)%>
	   <%= link_to "Unfollow", unfollow_users_path(:user => @user), :class => "btn btn-primary"%>
	<% else %>
	   <%= link_to "Follow", follow_users_path(:user => @user), :class => "btn btn-primary"%>
	<% end %>
 <%= render :partial => "shared/flash_messages", :locals => {:flash => flash} %>
		<% end %>
		
		</div>
		<br>
		<% if @user.followers(User).count > 0 %>
	   <%= link_to "Followers", followers_users_path(:user => @user)%>
	  <% end %>
	  <% if @user.followees(User).count > 0 %>
	   <%= link_to "Following", following_users_path(:user => @user)%>
	  <% end %>
	  <br>
		<button type="button" class="btn btn-inverse" disabled>Followers: <%= @user.followers(User).count %></button>

	</div>
</div>