config/routes.rb
SkinnyMinnie::Application.routes.draw do
  get "cart/index"

  get "cart/show"

  get "product/index"

  get "product/show"

  get "products/index"

  get "products/show"

  get "products/category"

  get "users/index"

  get "dashboard/index"

  get "dashboard/my_rentals"

  get "dashboard/my_credits"

  get "dashboard/my_invites"

  get "dashboard/my_faves"

  get "dashboard/edit_profile"

  get "tsmhome/index"

  devise_for :users

  get "home/index"
  resources :users do
  match 'show/:id' => 'user#show'
  collection do
    get 'follow'
    get 'unfollow'
    get 'followers'
    get 'following'
  end

end

  
  

  

   root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  acts_as_follow_store
   
end

app/models/like.rb
class Like < ActiveRecord::Base
  acts_as_like_store
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  acts_as_mention_store
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_follower
  acts_as_followable
  acts_as_liker
  acts_as_mentionable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :id, :login, :username, :email, :password, :password_confirmation, :remember_me, :profile_private
  # attr_accessible :title, :body

	  # Virtual attribute for authenticating by either username or email
	# This is in addition to a real persisted field like 'username'
	attr_accessor :login

	 def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
  end

  def my_rentals
  end

  def my_credits
  end

  def my_invites
  end

  def my_faves
  end

  def edit_profile
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      render "tsm/index", :layout  => 'tsm' 
    else
      render "index"
  end

end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end

  def category
  end
end

app/controllers/tsm_controller.rb
class TsmController < ApplicationController

  def index
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
def index
  @users = User.all

  respond_to do |format|
    format.html # index.html.erb
    format.xml  { render :xml => @users }
    end
end

def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
end

def followers
     @user = User.find(params[:user])
     @followers = @user.followers(User)
   
     response = {:user => @user, :followers => @followers}
     
     respond_to do |format|
      format.html  #followers.html.erb
      format.xml {render :xml => response}
    end
end

def following
     @user = User.find(params[:user])
     @following = @user.followees(User)

     response = {:user => @user, :following => @following}
     
     respond_to do |format|
      format.html  #following.html.erb
      format.xml {render :xml => response}
    end
end

def follow
  #do something like
  user = User.find(params[:user])
  current_user.follow!(user)
  redirect_to :back
  flash[:success] = "Followed!"
end

def unfollow
  #do something like
  user = User.find(params[:user])
  current_user.unfollow!(user)
  redirect_to :back
  flash[:success] = "Unfollwed!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

   def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

  	
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
	
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tsm_helper.rb
module TsmHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>SkinnyMinnie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>
	
  

    
    <div class="row-fluid">
      <div class="span12">
  		    <div class="navbar">
            <div class="navbar-inner">
<!--               <a class="brand" href="#">THE SKINNY MINNIE</a>
 -->              <ul class="nav pull-right">
              <% if user_signed_in? %>
               <%= render "shared/account-drop" %>
               
                <% else %>
                <%= render "shared/login-drop" %>
                 <% end %>
                  </ul>
            </div>
        </div>
   
  		
<%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>

  
  <title>SkinnyMinnie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	
  <p class="notice" style="display:none;"><%= notice %></p>
  <p class="alert" style="display:none;"><%= alert %></p>
    
    <div class="row-fluid">
      <div class="span12">
  		    <div class="navbar">
            <div class="navbar-inner">
              <a class="brand" href="#">THE SKINNY MINNIE</a>
              <ul class="nav pull-right">
              <% if user_signed_in? %>
               <%= render "shared/account-drop" %>
               
                <% else %>
                <%= render "shared/login-drop" %>
                 <% end %>
               </ul>
            </div>
        </div>

  		
<%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/tsm.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>SkinnyMinnie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>
	
  <p class="notice" style="display:none;"><%= notice %></p>
  <p class="alert" style="display:none;"><%= alert %></p>
    
    <div class="row-fluid">
      <div class="span12">
  		    <div class="navbar">
            <div class="navbar-inner">
              <a class="brand" href="#">THE SKINNY MINNIE</a>
               <ul class="nav pull-right">
              <% if user_signed_in? %>
               <%= render "shared/account-drop" %>
               
                <% else %>
                <%= render "shared/login-drop" %>
                 <% end %>
               </ul>
            </div>
        </div>

  		
<%= yield %>
  </div>
</div>
</body>
</html>

app/views/shared/_account-drop.html.erb
    <div class="user-logged-in"><%= current_user.username %></div>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

        <img class="navbarsmprofile" src="/assets/myprofile.png"></a>
     
     <ul class="dropdown-menu">
     	  <li><%= link_to 'Dashboard', dashboard_index_path %></li>
     	  <li class="divider"></li>
     	  <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
     </ul>
 </li>
 

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_login-box.html.erb
<div class="login-box">
  				<div class="main">
  					<%= render 'shared/signin-form' %>
  				</div>
  				
</div>

app/views/shared/_login-drop.html.erb
    <li class="dropdown ">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img class="navbarsmprofile" src="/assets/myprofile.png"></a></a>
     
     <ul class="dropdown-menu">
     	   <%= render "shared/login-box" %>

     </ul>
 </li>

app/views/shared/_loginandreg-box.html.erb
<div class="login-box">
  				<div class="left pull-left">
  					<%= render 'shared/signin-form' %>
  				</div>
  				<div class="right pull-right">
  					<%= render 'shared/register-form' %>
  				</div>
</div>

app/views/shared/_register-form.html.erb
<h1>Sign up</h1>

						<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |register| %>
						  <%= register.error_notification %>

						    <%= register.input :login, :required => true, :autofocus => true %>
						    <%= register.input :password, :required => true %>
						    <%= register.input :password_confirmation, :required => true %>
						     <%= register.button :submit, "Sign up" %>

						 
						<% end %>

app/views/shared/_signin-form.html.erb
<h1>Sign in</h1>

<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <%= f.input :login, :required => false, :autofocus => true %>
    <%= f.input :password, :required => false %>
    
    <%= f.button :submit, "Sign in" %>
  
<% end %>

<%= render "devise/shared/links" %>